db_file                 "~/.mpd/database"

input {
        plugin          "curl"
}
music_directory    "~/Music"

auto_update "yes"

audio_output {
        type            "pipewire"
        name            "Pipewire Output"
}
