#preload = /home/tiubo/Pictures/Приколы/99999.png
#$lol=piwiwks.jpg
#$piol=b441e250dd66204eccdf21271c6947c1.jpg
#$pilo1=piwoks.jpg
#$pow=piwow.jpg
#$poww=poww.jpg
#$pow1=pow1.jpg
#$pow2=pow2.jpg
#$poezda=photo_2025-09-30_23-33-54_1.jpg
#$poezda2=photo_2025-09-30_23-33-55.jpg
#$poezda2=photo_2025-09-30_23-33-55_1.jpg
#$char=photo_2025-09-30_21-05-18(1).jpg
#$field=98e6dba38f575abef18de3a3dfc6461b.jpg
#$field1=coverbelarus.jpg
$field=green7.jpg
preload = /home/tiubo/Pictures/Приколы/$field
wallpaper = eDP-1,/home/tiubo/Pictures/Приколы/$field
#$field=98e6dba38f575abef18de3a3dfc6461b.jpg
